### ISSUE TITLE
plugins-configs only accessible from within the .config/neovim directory

### ISSUE THREAD

**Issue by AlvaroPata** [smithbm2316/vimconf-2021#4]
Hi! I found your slides very interesting, it's a pity that you run out of time in the conference.

I followed the `lua_advanced_setup`, and I run into several errors. One of them being that the `plugins_configs` weren't accessible from outside the `.config/nvim` directory.
So, I had to end up putting all the plugin configurations in the main `init.lua` file... and now language servers and `TreeSitter` work in other directories.
Do you maybe know how to make them globally accessible from while following the same organizational logic?
Thanks!

**Comment by smithbm2316** [comment]
What exactly does your file structure look like? The `lua_advanced_setup` folder should essentially be the code that just gets copy-pasted into your `.config/nvim` directory. Apologies if that was not clear!

As far as LSP servers go, you'll want to make sure that you install those binaries globally on your system, however the respective LSP's tell you to in their READMEs or documentation. For example with `tsserver` since I am a web developer, I run `npm install -g typescript typescript-language-server` as per the [lspconfig documentation](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver)

**Comment by smithbm2316** [comment]
I just pushed an improvement to the `lua_advanced_config/lua/plugin_configs/init.lua` file. Apologies about that I just noticed the bug. I did some copy-pasting from my own config when I made this repo originally and didn't follow the same file structure. That file should now auto-`require` any plugin-specific configuration file that you place in the `lua_advanced_config/lua/plugin_configs` directory now be working properly with the same file structure that the `lua_advanced_setup` folder has

**Comment by AlvaroPata** [comment]
Thanks for looking into it!

**Comment by AlvaroPata** [comment]
One more question, you would have to `source plugin_configs` from the root `init.lua` file, right?

**Comment by smithbm2316** [comment]
🤦🏻‍♂️ Yes that is correct. I've updated the `lua_advanced_config/init.lua` to reflect that. By running the line `require('plugin_configs')`, Lua will go and find the `init.lua` file in that `plugin_configs` directory and `require` it. Sorry for the error, thank you for catching it!

**Comment by smithbm2316** [comment]
Closing for now, feel free to re-open if you are still having an issue with the setup! I'm hoping to make some updates to this in the near future with some improvements that came with a lot of recent Neovim updates (particularly with the keymap function wrapper!)
